#FROM theiaide/theia

#LABEL maintainer="ahkui <ahkui@outlook.com>"

#USER root

#RUN echo 'fs.inotify.max_user_watches=524288' >> /etc/sysctl.conf

#USER theia

#Se cambia itheia por Visual Code online

#Se cambia itheia por Visual Code online

FROM ghcr.io/coder/code-server:latest
# usuario, extensiones o ajustes opcionales aquí

